### ISSUE TITLE
DEFAULT keyword causes Seg Fault and other feature requests

### ISSUE THREAD

**Issue by vittvolt** [cmu-db/peloton#644]
Hi,

I'm in the constraint team and here are some problems we found:

- (**URGENT**)When trying to integrate with the newly added parser feature in #633 , I found that the query parsing gives a seg fault for basic case like CREATE TABLE test (id INT PRIMARY KEY, a INT DEFAULT 1). It passed the postgresparser_test because only the parse tree was built. During execution of the postgresparser it gives a seg fault some where around line 582 in postgresparser.cpp during a reinterpret_cast. 

- This one is not urgent, but it stalls us from creating proper constraints for multi columns. As mentioned in #625 , some updates have been made in create_statement.h. Yet I observe in postgresparser.cpp that when a table is created, each constraint is associated with a single column (a column bool attributes indicating whether it is part of primary key / unique). When executing the create statement the executor checks the attributes of each column to create the primary key constraint. This does not work for constraints that span multiple columns. Maybe adding a vector in create_statement.h with included column numbers for each constraint is a good way for us to handle, but I'm not sure what is a suggested solution.

Some more observations (again not urgent issue):
- Just out of curiosity In postgresparser.cpp from line 834 to line 860 in the if else clause, the code snippet is never touched during execution, and I wonder why it seems to handle primary key and foreign key constraints.

Please make any comments if you think I have missed something, thanks!

**Comment by hzxa21** [comment]
The first problem is solved in #645.
As for the second problem, I agree what you have proposed. The current layout for the create_statement.h is not a good design. You guys should refactor that as said in the comment of #625 and then we can add parser support for that.

F.Y.I
Table constraints are handled here: https://github.com/cmu-db/peloton/blob/master/src/parser/postgresparser.cpp#L827
Column constraints are handled here: https://github.com/cmu-db/peloton/blob/master/src/parser/postgresparser.cpp#L752

**Comment by vittvolt** [comment]
@luochenUmich @hzxa21  The seg fault still appears after executing 

**CREATE TABLE test (id INT PRIMARY KEY, a INT DEFAULT 10);
INSERT INTO test VALUES (2, DEFAULT);**

Would it be possible that you guys can add it to the postgresparser unit test ?

**Comment by vittvolt** [comment]
@hzxa21

**Comment by poojanilangekar** [comment]
Fixed in #645
