### ISSUE TITLE
Transaction does not work in terminal ?

### ISSUE THREAD

**Issue by vittvolt** [cmu-db/peloton#666]
BEGIN does not seem to create a separate transaction? Or the isolation level does not guarantee repeatable reads?

We tested by:

CREATE TABLE test (a INT PRIMARY KEY)

Transaction 1:
BEGIN;
INSERT INTO test VALUES (1);

And then transaction 2:
BEGIN 
SELECT * FROM test;

Then value 1 is actually shown in the result set.

**Comment by mengranwo** [comment]
Maybe that's because you are missing a semicolon after the second transaction(txn 2)??
I tried those sql on my terminal, it worked.

**Comment by yingjunwu** [comment]
I have reproduced the bug reported by @vittvolt. The major problem is that, using `psql` terminal, Peloton treats every single statement, even the `BEGIN` statement, as a transaction. When the user types in `INSERT INTO test VALUES(1)`, Peloton will directly begin a new transaction, insert the tuple into the table, and then commit the transaction. I am not sure whether the networking team @hanli32 @CHUYilei has solved this problem.

**Comment by yingjunwu** [comment]
@hanli32 @CHUYilei sorry but I cannot find your PR... Has your PR been merged?

**Comment by hanli32** [comment]
@yingjunwu I think I have already fixed the single statement txn problem and the PR #647 has been merged.

**Comment by yingjunwu** [comment]
@hanli32 I see. But I reproduced the bug on the master branch, which means that the single-statement transaction problem may still exist even with your PR merged. Could you test code provided by @vittvolt?

**Comment by yingjunwu** [comment]
@hanli32 An easy way to confirm the existance of single-statement transaction: print out something every time the `BeginTransaction` and `EndTransaction` functions in `timestamp_ordering_transaction_manager.cpp` (https://github.com/cmu-db/peloton/blob/master/src/concurrency/timestamp_ordering_transaction_manager.cpp) are invoked. You will see this pair of functions are invoked every time a new statement is issued.

**Comment by hanli32** [comment]
@yingjunwu I tested the code and I found that one or more transactions may begin and end when the peloton is processing a statement, but these transactions are not invoked by tcop. I guess some other components in the Peloton may begin a new transaction when it is processing certain kind of queries and I think this is not the single-statement transaction problem. The transaction in the tcop's stack will not end until it receives a commit or rollback command from the terminal.
I added a semicolon after the second BEGIN and result is correct (no value in the result set).

**Comment by yingjunwu** [comment]
After discussing with @hanli32, we found there's no transaction-related bug at all. The "bug" reported in this issue is due to the missing of a semicolon. The "single-statement transaction bug" I mentioned in my previous post also did not exist. However, Peloton falsely treats statements like `begin` and `end` (rather than `BEGIN` and `END`) as a single-statement transaction. This bug is reported in #688.
